#!/usr/bin/perl
use Font::Scripts::Volt;
use Getopt::Std;

getopts('a:l:t');

unless ($ARGV[0])
{
    die <<'EOT';
    make_volt [-a file] [-l ligtype] infile outfile
Creates a copy of the infile font file adding a VOLT table to it.

  -a file       Attachment Point database .xml file
  -l ligtype    first or last, specifies to add ligature classes and rules
EOT
}

$f = Font::Scripts::Volt->read_font($ARGV[0], $opt_a) || die "Can't read font information";

$f->make_classes(-ligatures => $opt_l);
$res = $f->out_volt(-ligatures => $opt_l);

$res =~ s/\n/\r/og;
$res .= "\000" x 7;
if ($opt_t)
{ print $res; }
else
{
    $f->{'font'}{'TSIV'} = Font::TTF::Table->new(dat => $res, PARENT => $f->{'font'});
    $f->{'font'}->out($ARGV[1]);
}
