#! /usr/bin/perl
use Font::TTF::Scripts::Volt;
use Getopt::Std;

getopts('t:');

$font = Font::TTF::Scripts::Volt->read_font($ARGV[0]) || die "Can't open font file $ARGV[0]";
if ($opt_t)
{
    my ($inf) = IO::File->new("< $opt_t") || die "Can't open file $opt_t";
    while (<$inf>)
    { $volt_text .= $_; }
    $inf->close;
}
elsif (defined $f->{'font'}{'TSIV'})
{ $volt_text = $f->{'font'}{'TSIV'}->read->{' dat'}; }
else
{ die "No VOLT table in the font, nothing to do"; }
$name = $font->{'font'}{'name'}->read->find_name(2);
$upem = $font->{'font'}{'head'}{'unitsPerEm'};
$font->{'font'}{'post'}->read;
$res = $font->parse_volt($volt_text);

print "<?xml version='1.0'?>\n<font name='$name' upem='$upem'>\n\n";
for ($i = 0; $i < scalar @{$res->{'glyphs'}}; $i++)
{
    $glyph = $res->{'glyphs'}[$i];
    print "<glyph GID='$i'";
    @unis = sort {$a <=> $b} @{$glyph->{'uni'}};
    printf(" UID='%04X'", $unis[0]) if ($unis[0]);
    $psname = $font->{'font'}{'post'}{'VAL'}[$i];
    print " PSName='$psname'" if ($psname);
    print " VoltId='$glyph->{name}'" if ($glyph->{'name'} && $glyph->{'name'} ne $psname);
    if ($glyph->{'points'} || $glyph->{'type'})
    {
        print ">\n";
        foreach $p (sort keys %{$glyph->{'points'}})
        {
            $n = $p;
            $n =~ s/^MARK_/_/o;
            print "    <point type='$n'>\n";
            print "        <location x='$glyph->{'points'}{$p}{'pos'}{'x'}[0]' y='$glyph->{'points'}{$p}{'pos'}{'y'}[0]'/>\n";
            print "    </point>\n";
        }
        print "    <property name='VOLT_type' value='$glyph->{'type'}'/>\n" if ($glyph->{'type'});
        print "</glyph>\n";
    }
    else
    {
        print "/>\n";
    }
}

print "\n</font>\n";

__END__

=head1 TITLE

volt2xml - create attachment point database from VOLT source in a TrueType Font

=head1 SYNOPSIS

  volt2xml [-t voltdat.txt] infile.ttf > outfile.xml

=head1 DESCRIPTION

volt2xml parses the volt source in a font to extract attachment point information
which it prints to stdout

=head1 SEE ALSO

ttfbuilder, make_volt, voltExportAnchors

=cut
