=head1 NAME

Font::TTF::Scripts - Smart font script supporting modules and scripts for TTF/OTF

=head1 DESCRIPTION

This module contains a number of useful programs for hacking with TTF files:

check_attach, eurofix, fret, hackos2, make_gdl, make_volt, psfix, thai2gdl,
thai2ot, thai2volt, ttfbuilder, ttfenc, ttfname, ttfremap, ttfsetver,
volt2xml, voltExportAnchors, voltFixup, voltImportAnchors

Highlights include:

  fret       - produces PDF report of an uninstalled font including all glyphs
  hackos2    - manipulates the OS/2 table of a font
  ttfbuilder - builds a font from another font, attaching glyphs, subsetting, etc.
  ttfname    - renames a font

=head1 AUTHOR

Martin Hosken L<Martin_Hosken@sil.org>
(see CONTRIBUTORS for other authors).

=head1 LICENSING

Copyright (c) 1998-2013, SIL International (http://www.sil.org)

This module and all the various scripts are released under the terms of the
Artistic License 2.0. For details, see the full text of the license in the file
LICENSE.

The test suite contains test fonts released under the Open Font License v1.1, see OFL.txt.

